name: Hexo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.6.0
        with:
          enable-cache: 'true'
          refresh-cli: 'true'
      - name: Install dependencies
        run: pnpm install
      - name: Clean
        run: pnpm run clean
      - name: Build
        run: pnpm run build
        env:
          gitalk_id: ${{ secrets.GITALK_ID }}
          gitalk_secret: ${{ secrets.GITALK_SECRET }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGE }}
          publish_dir: ./public
          publish_branch: main  # default: gh-pages
